### ISSUE TITLE
Cannot find commander

### ISSUE THREAD

**Issue by hdavy2002** [xkxx/node-spdy-proxy#2]
I am getting this error

hdavy2002@zip:~/node-spdy-proxy-master$ sudo ./runserver proxy.conf

module.js:340
    throw err;
          ^
Error: Cannot find module 'commander'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/hdavy2002/node-spdy-proxy-master/runserver:3:15)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
hdavy2002@zip:~/node-spdy-proxy-master$

**Comment by xkxx** [comment]
Hi hdavy2002,

Sorry about your issue. You have to do `npm install` in the node-spdy-proxy directory before you run the server.
