### ISSUE TITLE
./runserver encountered error,how to fix it?

### ISSUE THREAD

**Issue by luckypoem** [xkxx/node-spdy-proxy#6]
hi.

root@ar:~/node-spdy-proxy# ./runserver
util.js:948
    throw new errors.TypeError('ERR_INVALID_ARG_TYPE', 'superCtor', 'Function');
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "superCtor" argument must be of type Function
    at Object.inherits (util.js:948:11)
    at Object.<anonymous> (/root/node-spdy-proxy/node_modules/spdy/lib/spdy/server.js:478:6)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
    at Module.require (module.js:593:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/root/node-spdy-proxy/node_modules/spdy/lib/spdy.js:31:15)
root@ar:~/node-spdy-proxy#

**Comment by luckypoem** [comment]
install node v4.1.0 ,can fix it
